

#%RAML 1.0 NamedExample
value:
  -
    id: 10
    eventtypeid: 33
    eventname: New Student Enrollment
    exchangename: capella.direct
    exchangetype: direct
    queuename: new.student.enrollment
  -
    id: 2
    eventtypeid: 45
    eventname: New Course 2019
    exchangename: capella.fanout
    exchangetype: fanout
    queuename: new.course.2019                                                                                     